### ISSUE TITLE
Seeing error when attempting to use auth-jwt branch migrations

### ISSUE THREAD

**Issue by mwarger** [hgiasac/hasura-typescript-boilerplate#13]
I'm seeing an error when starting the server using the auth-jwt migrations:

```
",\"prepared\":false,\"error\":{\"exec_status\":\"FatalError\",\"hint\":null,\"message\":\"relation \\\"hdb_catalog.hdb_role\\\" does not exist\",\"status_code\":\"42P01\",\"description\":null},\"arguments\":[]},\"path\":\"$\",\"error\":\"query execution failed\",\"code\":\"postgres-error\"}"
```

This is using v2 - it seems this is happening based on the migration to create the `roles` view.  It's not able to find the schema and table that's needed.  Is there some setup that I'm missing?  

Thanks for making this boilerplate, it's been informative.

**Comment by hgiasac** [comment]
Sorry for the late reply. These are v1.3.3 migrations. Hasura 2.0 migrations and metadata structures are different now (v3 metadata)
I will update migrations for Hasura 2.0 soon
