### ISSUE TITLE
Add Hasura migration data

### ISSUE THREAD

**Issue by cpursley** [hgiasac/hasura-typescript-boilerplate#3]
services/data/migrations is missing Hasura migrations files

**Comment by hgiasac** [comment]
Are you on `master` branch? It is expected. If you use jwt auth, checkout to `auth-jwt` branch, or `auth-firebase`

**Comment by cpursley** [comment]
`auth-jwt` branch worked, thank you. I recommend adding notes about the need to check out the specific branch to the README.

**Comment by hgiasac** [comment]
Closed by https://github.com/hgiasac/hasura-typescript-boilerplate/commit/4dde459e25ecbddcfd2f457f273a0ccb8cc0d3a5
